### ISSUE TITLE
请求授权：）

### ISSUE THREAD

**Issue by drinktoomuchsax** [deepoceansame/SUSTECH_EE205_SignalAndSystem#2]
hallo，能否在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及使用你的文件。

**Comment by deepoceansame** [comment]
行 加个乱得要死标签

**Comment by drinktoomuchsax** [comment]
yesir
